<a href="https://colab.research.google.com/github/vihaveman/Deep_Learning_Challenge/blob/main/AlphabetSoupCharity_Optimization_ipynb_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:

# Drop the non-beneficial ID columns, 'EIN'.
application_df = application_df.drop(columns = ['EIN'])

In [3]:
# Determine the number of unique values in each column.
application_df.nunique()

NAME                      19568
APPLICATION_TYPE             17
AFFILIATION                   6
CLASSIFICATION               71
USE_CASE                      5
ORGANIZATION                  4
STATUS                        2
INCOME_AMT                    9
SPECIAL_CONSIDERATIONS        2
ASK_AMT                    8747
IS_SUCCESSFUL                 2
dtype: int64

In [5]:
# Look at NAME counts for binning
counts_opt = application_df['NAME'].value_counts()
counts_opt

PARENT BOOSTER USA INC                                                  1260
TOPS CLUB INC                                                            765
UNITED STATES BOWLING CONGRESS INC                                       700
WASHINGTON STATE UNIVERSITY                                              492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC                          408
                                                                        ...
ST LOUIS SLAM WOMENS FOOTBALL                                              1
AIESEC ALUMNI IBEROAMERICA CORP                                            1
WEALLBLEEDRED ORG INC                                                      1
AMERICAN SOCIETY FOR STANDARDS IN MEDIUMSHIP & PSYCHICAL INVESTIGATI       1
WATERHOUSE CHARITABLE TR                                                   1
Name: NAME, Length: 19568, dtype: int64

In [10]:
# Choose a cutoff value and create a list of names_replace to be replaced
# use the variable name names_replace
names_replace = list(counts_opt[counts_opt<5].index)
names_replace[:10]

['AMALGAMATED TRANSIT UNION',
 '4-H CLUBS & AFFILIATED 4-H ORGANIZATIONS',
 'TEXAS WATER UTILITIES ASSOCIATION',
 'PARENTS FAMILIES AND FRIENDS OF LESBIANS AND GAYS INC',
 'THE UNITED STATE PONY CLUBS INC',
 'WESTERN GOVERNORS UNIVERSITY',
 'AMERICAN ORFF-SCHULWERK ASSOCIATION',
 'GAMMA PHI BETA SORORITY INC',
 'AMATEUR ATHLETIC UNION OV THE UNITED STATES INC',
 'DEPARTMENT OF OKLAHOMA LADIES AUXILIARY TO THE VFW INC']

In [11]:
# Replace in dataframe
for name in names_replace:
    application_df['NAME'] = application_df['NAME'].replace(name,"Other")

# Check to make sure binning was successful
application_df['NAME'].value_counts()

Other                                                                19803
PARENT BOOSTER USA INC                                                1260
TOPS CLUB INC                                                          765
UNITED STATES BOWLING CONGRESS INC                                     700
WASHINGTON STATE UNIVERSITY                                            492
                                                                     ...
GUILDS OF THE SANTA FE OPERA INC                                         5
FAMILY MOTOR COACH ASSOCIATION                                           5
JAMESTOWN SOCIETY                                                        5
MOST WORSHIPFUL PRINCE HALL GRAND LODGE OF FREE & ACCEPTED MASONS        5
PTA HAWAII CONGRESS                                                      5
Name: NAME, Length: 403, dtype: int64

In [12]:
# Look at APPLICATION TYPE counts for binning
counts = application_df['APPLICATION_TYPE'].value_counts()
counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [15]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(counts[counts<500].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [16]:
# Look at CLASSIFICATION value counts for binning
countsbinning = application_df['CLASSIFICATION'].value_counts()

In [54]:

# You may find it helpful to look at CLASSIFICATION value counts >1
countsclassification = countsbinning[countsbinning>1]
countsclassification

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [21]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list (countsbinning[countsbinning<1000].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [22]:

# Convert categorical data to numeric with `pd.get_dummies`
application_df = pd.get_dummies(application_df,dtype=float)
application_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,NAME_AACE INTERNATIONAL,NAME_ACE MENTOR PROGRAM OF AMERICA INC,NAME_ACTS MINISTRY,NAME_ACTS MISSIONS,NAME_AFRICAN-AMERICAN POSTAL LEAGUE UNITED FOR SUCCESS A-PLUS,NAME_AIR FORCE ASSOCIATION,NAME_ALABAMA FEDERATION OF WOMENS CLUBS,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [41]:
# Split our preprocessed data into our features and target arrays

# Separate the y variable (target arrays)
y = application_df['IS_SUCCESSFUL'].values

# Separate the X variable (features)
X = application_df.drop('IS_SUCCESSFUL', axis=1).values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state = 42)

In [42]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [47]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len( X_train_scaled[0])
hidden_nodes_layer1=7
hidden_nodes_layer2=14
hidden_nodes_layer3=21

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation='relu'))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_17 (Dense)            (None, 7)                 3129

 dense_18 (Dense)            (None, 14)                112

 dense_19 (Dense)            (None, 1)                 15

=================================================================
Total params: 3,256
Trainable params: 3,256
Non-trainable params: 0
_________________________________________________________________

In [48]:

# Compile the model
nn.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])

In [49]:

# Train the model
fit_model = nn.fit(X_train_scaled,y_train,validation_split=0.15, epochs=100)

Epoch 1/100
684/684 [==============================] - 3s 3ms/step - loss: 0.5502 - accuracy: 0.7344 - val_loss: 0.4630 - val_accuracy: 0.7709
Epoch 2/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4565 - accuracy: 0.7774 - val_loss: 0.4355 - val_accuracy: 0.7917
Epoch 3/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4377 - accuracy: 0.7858 - val_loss: 0.4323 - val_accuracy: 0.7927
Epoch 4/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4321 - accuracy: 0.7890 - val_loss: 0.4326 - val_accuracy: 0.7966
Epoch 5/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4294 - accuracy: 0.7887 - val_loss: 0.4303 - val_accuracy: 0.7976
Epoch 6/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4275 - accuracy: 0.7907 - val_loss: 0.4328 - val_accuracy: 0.7942
Epoch 7/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4264 - accuracy: 0.7923 - val_loss: 0.4347 - val_accuracy: 0.7963
Epoch 8/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4247 - accuracy: 0.7941 - val_loss: 0.4320 - val_accuracy: 0.7994
Epoch 9/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4236 - accuracy: 0.7953 - val_loss: 0.4357 - val_accuracy: 0.7963
Epoch 10/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4227 - accuracy: 0.7973 - val_loss: 0.4333 - val_accuracy: 0.7981
Epoch 11/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4221 - accuracy: 0.7962 - val_loss: 0.4359 - val_accuracy: 0.7971
Epoch 12/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4215 - accuracy: 0.7960 - val_loss: 0.4326 - val_accuracy: 0.7999
Epoch 13/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4208 - accuracy: 0.7968 - val_loss: 0.4318 - val_accuracy: 0.8018
Epoch 14/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4187 - accuracy: 0.7968 - val_loss: 0.4321 - val_accuracy: 0.7961
Epoch 15/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4180 - accuracy: 0.7960 - val_loss: 0.4322 - val_accuracy: 0.7992
Epoch 16/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4173 - accuracy: 0.7971 - val_loss: 0.4323 - val_accuracy: 0.8002
Epoch 17/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4169 - accuracy: 0.7982 - val_loss: 0.4318 - val_accuracy: 0.8049
Epoch 18/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4165 - accuracy: 0.7984 - val_loss: 0.4322 - val_accuracy: 0.8069
Epoch 19/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4162 - accuracy: 0.7984 - val_loss: 0.4314 - val_accuracy: 0.8033
Epoch 20/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4159 - accuracy: 0.7986 - val_loss: 0.4326 - val_accuracy: 0.8044
Epoch 21/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4156 - accuracy: 0.7995 - val_loss: 0.4308 - val_accuracy: 0.8041
Epoch 22/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4151 - accuracy: 0.7992 - val_loss: 0.4339 - val_accuracy: 0.8049
Epoch 23/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4148 - accuracy: 0.7997 - val_loss: 0.4339 - val_accuracy: 0.8049
Epoch 24/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4147 - accuracy: 0.8009 - val_loss: 0.4348 - val_accuracy: 0.8049
Epoch 25/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4147 - accuracy: 0.8001 - val_loss: 0.4333 - val_accuracy: 0.8041
Epoch 26/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4139 - accuracy: 0.8003 - val_loss: 0.4321 - val_accuracy: 0.8033
Epoch 27/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4138 - accuracy: 0.8012 - val_loss: 0.4334 - val_accuracy: 0.8028
Epoch 28/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4139 - accuracy: 0.8016 - val_loss: 0.4351 - val_accuracy: 0.8020
Epoch 29/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4136 - accuracy: 0.8005 - val_loss: 0.4341 - val_accuracy: 0.7987
Epoch 30/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4128 - accuracy: 0.8012 - val_loss: 0.4359 - val_accuracy: 0.8031
Epoch 31/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4128 - accuracy: 0.8013 - val_loss: 0.4337 - val_accuracy: 0.8036
Epoch 32/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4127 - accuracy: 0.8014 - val_loss: 0.4323 - val_accuracy: 0.8033
Epoch 33/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4126 - accuracy: 0.8022 - val_loss: 0.4365 - val_accuracy: 0.8049
Epoch 34/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4120 - accuracy: 0.8017 - val_loss: 0.4363 - val_accuracy: 0.8010
Epoch 35/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4123 - accuracy: 0.8019 - val_loss: 0.4361 - val_accuracy: 0.8007
Epoch 36/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4117 - accuracy: 0.8027 - val_loss: 0.4362 - val_accuracy: 0.8031
Epoch 37/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4117 - accuracy: 0.8027 - val_loss: 0.4337 - val_accuracy: 0.8059
Epoch 38/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4112 - accuracy: 0.8022 - val_loss: 0.4382 - val_accuracy: 0.8036
Epoch 39/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4112 - accuracy: 0.8022 - val_loss: 0.4365 - val_accuracy: 0.8020
Epoch 40/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4111 - accuracy: 0.8026 - val_loss: 0.4373 - val_accuracy: 0.8036
Epoch 41/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4110 - accuracy: 0.8027 - val_loss: 0.4368 - val_accuracy: 0.8015
Epoch 42/100
684/684 [==============================] - 3s 4ms/step - loss: 0.4110 - accuracy: 0.8030 - val_loss: 0.4360 - val_accuracy: 0.7994
Epoch 43/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4104 - accuracy: 0.8027 - val_loss: 0.4347 - val_accuracy: 0.7984
Epoch 44/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4103 - accuracy: 0.8033 - val_loss: 0.4383 - val_accuracy: 0.8023
Epoch 45/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4104 - accuracy: 0.8042 - val_loss: 0.4366 - val_accuracy: 0.8023
Epoch 46/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4103 - accuracy: 0.8039 - val_loss: 0.4362 - val_accuracy: 0.8020
Epoch 47/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4099 - accuracy: 0.8022 - val_loss: 0.4397 - val_accuracy: 0.8018
Epoch 48/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4101 - accuracy: 0.8028 - val_loss: 0.4388 - val_accuracy: 0.8046
Epoch 49/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4098 - accuracy: 0.8028 - val_loss: 0.4409 - val_accuracy: 0.8007
Epoch 50/100
684/684 [==============================] - 2s 4ms/step - loss: 0.4096 - accuracy: 0.8044 - val_loss: 0.4408 - val_accuracy: 0.8023
Epoch 51/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4097 - accuracy: 0.8036 - val_loss: 0.4398 - val_accuracy: 0.8038
Epoch 52/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4098 - accuracy: 0.8039 - val_loss: 0.4395 - val_accuracy: 0.8036
Epoch 53/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4093 - accuracy: 0.8040 - val_loss: 0.4393 - val_accuracy: 0.7987
Epoch 54/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4094 - accuracy: 0.8036 - val_loss: 0.4397 - val_accuracy: 0.7989
Epoch 55/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4093 - accuracy: 0.8041 - val_loss: 0.4391 - val_accuracy: 0.8012
Epoch 56/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4089 - accuracy: 0.8041 - val_loss: 0.4403 - val_accuracy: 0.8010
Epoch 57/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4090 - accuracy: 0.8038 - val_loss: 0.4411 - val_accuracy: 0.8012
Epoch 58/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4089 - accuracy: 0.8040 - val_loss: 0.4409 - val_accuracy: 0.8020
Epoch 59/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4094 - accuracy: 0.8034 - val_loss: 0.4377 - val_accuracy: 0.8018
Epoch 60/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4091 - accuracy: 0.8043 - val_loss: 0.4413 - val_accuracy: 0.8005
Epoch 61/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4087 - accuracy: 0.8042 - val_loss: 0.4419 - val_accuracy: 0.8015
Epoch 62/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4087 - accuracy: 0.8042 - val_loss: 0.4385 - val_accuracy: 0.8025
Epoch 63/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4086 - accuracy: 0.8039 - val_loss: 0.4403 - val_accuracy: 0.8038
Epoch 64/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4086 - accuracy: 0.8028 - val_loss: 0.4405 - val_accuracy: 0.8031
Epoch 65/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4088 - accuracy: 0.8037 - val_loss: 0.4411 - val_accuracy: 0.8005
Epoch 66/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4080 - accuracy: 0.8038 - val_loss: 0.4406 - val_accuracy: 0.8044
Epoch 67/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4081 - accuracy: 0.8038 - val_loss: 0.4421 - val_accuracy: 0.8018
Epoch 68/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4082 - accuracy: 0.8036 - val_loss: 0.4414 - val_accuracy: 0.8028
Epoch 69/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4080 - accuracy: 0.8033 - val_loss: 0.4422 - val_accuracy: 0.8031
Epoch 70/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4085 - accuracy: 0.8046 - val_loss: 0.4387 - val_accuracy: 0.8041
Epoch 71/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4083 - accuracy: 0.8041 - val_loss: 0.4411 - val_accuracy: 0.8038
Epoch 72/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4081 - accuracy: 0.8043 - val_loss: 0.4422 - val_accuracy: 0.8028
Epoch 73/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4077 - accuracy: 0.8043 - val_loss: 0.4411 - val_accuracy: 0.8028
Epoch 74/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4079 - accuracy: 0.8041 - val_loss: 0.4417 - val_accuracy: 0.8038
Epoch 75/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4076 - accuracy: 0.8042 - val_loss: 0.4420 - val_accuracy: 0.7968
Epoch 76/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4078 - accuracy: 0.8041 - val_loss: 0.4406 - val_accuracy: 0.8020
Epoch 77/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4077 - accuracy: 0.8043 - val_loss: 0.4435 - val_accuracy: 0.8007
Epoch 78/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4078 - accuracy: 0.8041 - val_loss: 0.4407 - val_accuracy: 0.8002
Epoch 79/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4075 - accuracy: 0.8042 - val_loss: 0.4390 - val_accuracy: 0.8015
Epoch 80/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4076 - accuracy: 0.8051 - val_loss: 0.4414 - val_accuracy: 0.8012
Epoch 81/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4077 - accuracy: 0.8053 - val_loss: 0.4400 - val_accuracy: 0.8020
Epoch 82/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4078 - accuracy: 0.8042 - val_loss: 0.4394 - val_accuracy: 0.8025
Epoch 83/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4071 - accuracy: 0.8049 - val_loss: 0.4414 - val_accuracy: 0.8010
Epoch 84/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4072 - accuracy: 0.8044 - val_loss: 0.4425 - val_accuracy: 0.8023
Epoch 85/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4075 - accuracy: 0.8046 - val_loss: 0.4400 - val_accuracy: 0.8002
Epoch 86/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4071 - accuracy: 0.8047 - val_loss: 0.4417 - val_accuracy: 0.8015
Epoch 87/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4074 - accuracy: 0.8046 - val_loss: 0.4401 - val_accuracy: 0.8005
Epoch 88/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4072 - accuracy: 0.8049 - val_loss: 0.4437 - val_accuracy: 0.8010
Epoch 89/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4069 - accuracy: 0.8045 - val_loss: 0.4420 - val_accuracy: 0.7999
Epoch 90/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4069 - accuracy: 0.8053 - val_loss: 0.4411 - val_accuracy: 0.8018
Epoch 91/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4073 - accuracy: 0.8045 - val_loss: 0.4401 - val_accuracy: 0.8020
Epoch 92/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4071 - accuracy: 0.8048 - val_loss: 0.4417 - val_accuracy: 0.8010
Epoch 93/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4070 - accuracy: 0.8056 - val_loss: 0.4439 - val_accuracy: 0.8010
Epoch 94/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4069 - accuracy: 0.8050 - val_loss: 0.4429 - val_accuracy: 0.7999
Epoch 95/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4069 - accuracy: 0.8048 - val_loss: 0.4470 - val_accuracy: 0.7992
Epoch 96/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4067 - accuracy: 0.8056 - val_loss: 0.4447 - val_accuracy: 0.7974
Epoch 97/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4073 - accuracy: 0.8043 - val_loss: 0.4418 - val_accuracy: 0.8012
Epoch 98/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4068 - accuracy: 0.8045 - val_loss: 0.4422 - val_accuracy: 0.8010
Epoch 99/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4069 - accuracy: 0.8043 - val_loss: 0.4462 - val_accuracy: 0.8010
Epoch 100/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4067 - accuracy: 0.8045 - val_loss: 0.4408 - val_accuracy: 0.8018

In [50]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.4661 - accuracy: 0.7896 - 523ms/epoch - 2ms/step
Loss: 0.4660731256008148, Accuracy: 0.7896209955215454

In [52]:
# Export our model to HDF5 file
from google.colab import files

nn.save('/content/AlphabetSoupCharity_Optimization.h5')
files.download('/content/AlphabetSoupCharity_Optimization.h5')